"""empty message

Revision ID: 1686b8a6e283
Revises: None
Create Date: 2015-01-04 16:37:09.524964

"""

# revision identifiers, used by Alembic.
revision = '1686b8a6e283'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('exercise_type', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    ### end Alembic commands ###
