"""empty message

Revision ID: 2168ae430dbc
Revises: 1686b8a6e283
Create Date: 2015-01-06 15:59:13.715283

"""

# revision identifiers, used by Alembic.
revision = '2168ae430dbc'
down_revision = '1686b8a6e283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'exercises', sa.Column('equipment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'equipment', ['equipment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column(u'exercises', 'equipment_id')
    op.drop_table('equipment')
    ### end Alembic commands ###
