"""empty message

Revision ID: 2901b5a4531c
Revises: 298d33be2a06
Create Date: 2015-01-06 17:19:40.637267

"""

# revision identifiers, used by Alembic.
revision = '2901b5a4531c'
down_revision = '298d33be2a06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
