"""empty message

Revision ID: 298d33be2a06
Revises: 44bcf4e5af27
Create Date: 2015-01-06 16:46:56.739389

"""

# revision identifiers, used by Alembic.
revision = '298d33be2a06'
down_revision = '44bcf4e5af27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('exercises', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'exercise_type',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('exercises', 'exercise_type',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('exercises', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    ### end Alembic commands ###
