"""empty message

Revision ID: 35bfd9b5554a
Revises: 5762f8505fdf
Create Date: 2015-01-16 15:27:52.818911

"""

# revision identifiers, used by Alembic.
revision = '35bfd9b5554a'
down_revision = '5762f8505fdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
