"""empty message

Revision ID: 3ede02e68879
Revises: 35bfd9b5554a
Create Date: 2015-01-16 15:28:31.440933

"""

# revision identifiers, used by Alembic.
revision = '3ede02e68879'
down_revision = '35bfd9b5554a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
