"""empty message

Revision ID: 3f9b5ae5be24
Revises: 5799ccbb5e83
Create Date: 2015-01-06 17:21:23.130446

"""

# revision identifiers, used by Alembic.
revision = '3f9b5ae5be24'
down_revision = '5799ccbb5e83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
