"""empty message

Revision ID: 40aebeb6d406
Revises: b62aa6824d8
Create Date: 2015-01-16 15:48:47.436371

"""

# revision identifiers, used by Alembic.
revision = '40aebeb6d406'
down_revision = 'b62aa6824d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_type', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'exercise_type')
    ### end Alembic commands ###
