"""empty message

Revision ID: 44bcf4e5af27
Revises: 2168ae430dbc
Create Date: 2015-01-06 16:07:46.891005

"""

# revision identifiers, used by Alembic.
revision = '44bcf4e5af27'
down_revision = '2168ae430dbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
