"""empty message

Revision ID: 4e2329556694
Revises: 501118a6094
Create Date: 2015-01-17 16:38:23.368335

"""

# revision identifiers, used by Alembic.
revision = '4e2329556694'
down_revision = '501118a6094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column(u'entries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    op.alter_column(u'exercises', 'exercise_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text(u"'strength'::character varying"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'exercises', 'exercise_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text(u"'strength'::character varying"))
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column(u'entries', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
