"""empty message

Revision ID: 501118a6094
Revises: 40aebeb6d406
Create Date: 2015-01-16 15:49:14.206837

"""

# revision identifiers, used by Alembic.
revision = '501118a6094'
down_revision = '40aebeb6d406'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    return
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'exercise_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###
