"""empty message

Revision ID: 53e2e2585fd8
Revises: 4e2329556694
Create Date: 2015-01-17 16:40:19.981630

"""

# revision identifiers, used by Alembic.
revision = '53e2e2585fd8'
down_revision = '4e2329556694'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###
