"""empty message

Revision ID: 5799ccbb5e83
Revises: 2901b5a4531c
Create Date: 2015-01-06 17:21:09.156412

"""

# revision identifiers, used by Alembic.
revision = '5799ccbb5e83'
down_revision = '2901b5a4531c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
