"""empty message

Revision ID: 87cac432e0c
Revises: 53e2e2585fd8
Create Date: 2015-01-17 17:40:26.319849

"""

# revision identifiers, used by Alembic.
revision = '87cac432e0c'
down_revision = '53e2e2585fd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
