"""empty message

Revision ID: b62aa6824d8
Revises: ca460edc2dd
Create Date: 2015-01-16 15:31:58.173798

"""

# revision identifiers, used by Alembic.
revision = 'b62aa6824d8'
down_revision = 'ca460edc2dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    return
    op.add_column('exercises', sa.Column('exercise_type', sa.String(length=10), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'exercise_type')
    ### end Alembic commands ###
