"""empty message

Revision ID: ca460edc2dd
Revises: daa0745edd6
Create Date: 2015-01-16 15:31:39.687399

"""

# revision identifiers, used by Alembic.
revision = 'ca460edc2dd'
down_revision = 'daa0745edd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('exercises', 'exercise_type')
    return
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
