"""empty message

Revision ID: daa0745edd6
Revises: 3ede02e68879
Create Date: 2015-01-16 15:29:05.399836

"""

# revision identifiers, used by Alembic.
revision = 'daa0745edd6'
down_revision = '3ede02e68879'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
